server:
  port: 8082

spring:
  application:
    name: event-generator-service

app:
  kafka:
    bootstrap-servers: kafka:9092
    topic: user-events

logging:
  level:
    root: INFO
    reactor.kafka: DEBUG
